// ArchLens — Artifact Reference Service
// Provides access to architecture and project artifact templates

import * as fs from 'fs';
import * as path from 'path';
import log from 'electron-log';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ArtifactCategory =
  | 'architecture'
  | 'project-management'
  | 'governance'
  | 'delivery'
  | 'security'
  | 'data'
  | 'service-design'
  | 'operations'
  | 'commercial';

export type ProjectPhase =
  | 'discovery'
  | 'alpha'
  | 'beta'
  | 'live'
  | 'retirement'
  | 'pre-discovery'
  | 'throughout';

export interface TemplateSection {
  heading: string;
  guidance: string;
  placeholder: string;
}

export interface Artifact {
  id: string;
  name: string;
  category: ArtifactCategory;
  subcategory: string;
  description: string;
  purpose: string;
  whenToUse: string;
  projectPhase: ProjectPhase[];
  frameworks: string[];
  audience: string[];
  howToBuild: string;
  tips: string[];
  commonMistakes: string[];
  governmentContext: string;
  relatedArtifacts: string[];
  templateSections: TemplateSection[];
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

export class ArtifactService {
  private artifacts: Artifact[] = [];

  /**
   * Loads artifacts from the JSON data file.
   */
  loadArtifacts(filePath: string): void {
    try {
      const raw = fs.readFileSync(filePath, 'utf-8');
      const data = JSON.parse(raw);
      this.artifacts = data.artifacts ?? [];
      log.info(`Loaded ${this.artifacts.length} artifacts from ${filePath}`);
    } catch (err) {
      log.error('Failed to load artifacts:', err);
      this.artifacts = [];
    }
  }

  /**
   * Returns all artifacts.
   */
  getAll(): Artifact[] {
    return this.artifacts;
  }

  /**
   * Filters artifacts by category.
   */
  getByCategory(category: ArtifactCategory): Artifact[] {
    return this.artifacts.filter((a) => a.category === category);
  }

  /**
   * Filters artifacts by project phase.
   */
  getByPhase(phase: ProjectPhase): Artifact[] {
    return this.artifacts.filter((a) => a.projectPhase.includes(phase));
  }

  /**
   * Filters artifacts by framework reference.
   */
  getByFramework(framework: string): Artifact[] {
    const lower = framework.toLowerCase();
    return this.artifacts.filter((a) =>
      a.frameworks.some((f) => f.toLowerCase().includes(lower)),
    );
  }

  /**
   * Searches artifacts by name, description, subcategory, or purpose.
   */
  search(query: string): Artifact[] {
    const lower = query.toLowerCase().trim();
    if (!lower) return this.artifacts;

    return this.artifacts.filter(
      (a) =>
        a.name.toLowerCase().includes(lower) ||
        a.description.toLowerCase().includes(lower) ||
        a.subcategory.toLowerCase().includes(lower) ||
        a.purpose.toLowerCase().includes(lower),
    );
  }

  /**
   * Returns a single artifact by ID.
   */
  getById(id: string): Artifact | null {
    return this.artifacts.find((a) => a.id === id) ?? null;
  }

  /**
   * Generates a Markdown template string for the given artifact.
   * Returns the formatted Markdown content.
   */
  generateMarkdownTemplate(artifactId: string): string {
    const artifact = this.getById(artifactId);
    if (!artifact) {
      throw new Error(`Artifact not found: ${artifactId}`);
    }

    const lines: string[] = [];

    // Title and metadata
    lines.push(`# ${artifact.name}`);
    lines.push('');
    lines.push(`**Date:** [Date]`);
    lines.push(`**Author:** [Author Name]`);
    lines.push(`**Version:** 1.0`);
    lines.push(`**Status:** Draft`);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Purpose
    lines.push('## Purpose');
    lines.push('');
    lines.push(`> ${artifact.purpose}`);
    lines.push('');

    // Template sections
    for (const section of artifact.templateSections) {
      lines.push(`## ${section.heading}`);
      lines.push('');
      lines.push(`<!-- Guidance: ${section.guidance} -->`);
      lines.push('');
      lines.push(section.placeholder);
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by ArchLens — ${new Date().toLocaleDateString('en-GB')}*`);

    return lines.join('\n');
  }

  /**
   * Generates a .docx template file for the given artifact.
   * Returns the file path of the generated document.
   */
  async generateTemplate(artifactId: string, outputDir: string): Promise<string> {
    const artifact = this.getById(artifactId);
    if (!artifact) {
      throw new Error(`Artifact not found: ${artifactId}`);
    }

    // Dynamic import of docx to avoid issues if not installed
    const {
      Document,
      Packer,
      Paragraph,
      TextRun,
      HeadingLevel,
      AlignmentType,
      BorderStyle,
    // @ts-ignore — docx is an optional dependency for .docx generation
    } = await import('docx');

    const children: InstanceType<typeof Paragraph>[] = [];

    // Title page
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 3000 },
        children: [
          new TextRun({
            text: artifact.name,
            bold: true,
            size: 56,
            color: '1a1a2e',
          }),
        ],
      }),
    );

    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 400 },
        children: [
          new TextRun({
            text: `Category: ${artifact.category.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}`,
            size: 24,
            color: '666666',
          }),
        ],
      }),
    );

    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 200 },
        children: [
          new TextRun({
            text: `Generated by ArchLens — ${new Date().toLocaleDateString('en-GB')}`,
            size: 20,
            color: '999999',
            italics: true,
          }),
        ],
      }),
    );

    // Page break after title
    children.push(
      new Paragraph({
        spacing: { before: 200 },
        children: [],
        pageBreakBefore: true,
      }),
    );

    // Purpose section
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: 'Purpose', bold: true })],
      }),
    );
    children.push(
      new Paragraph({
        spacing: { after: 200 },
        children: [new TextRun({ text: artifact.purpose, italics: true, color: '555555' })],
      }),
    );

    // Guidance section
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: 'How to Complete This Document', bold: true })],
      }),
    );
    children.push(
      new Paragraph({
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: 'Each section below includes guidance in italics. Replace the guidance text with your content.',
            italics: true,
            color: '555555',
          }),
        ],
      }),
    );

    // Separator
    children.push(
      new Paragraph({
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: 'CCCCCC' },
        },
        spacing: { after: 400 },
        children: [],
      }),
    );

    // Template sections
    for (const section of artifact.templateSections) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 400 },
          children: [new TextRun({ text: section.heading, bold: true })],
        }),
      );

      children.push(
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({
              text: section.guidance,
              italics: true,
              color: '666666',
            }),
          ],
        }),
      );

      // Placeholder content
      children.push(
        new Paragraph({
          spacing: { before: 100, after: 200 },
          children: [
            new TextRun({ text: section.placeholder, color: '888888' }),
          ],
        }),
      );

      // Empty paragraph for user to fill in
      children.push(
        new Paragraph({
          spacing: { after: 300 },
          children: [new TextRun({ text: '', color: 'AAAAAA' })],
        }),
      );
    }

    const doc = new Document({
      sections: [{ children }],
    });

    const buffer = await Packer.toBuffer(doc);
    const sanitisedName = artifact.name.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-');
    const fileName = `${sanitisedName}-Template.docx`;
    const outputPath = path.join(outputDir, fileName);

    fs.writeFileSync(outputPath, buffer);
    log.info(`Generated template: ${outputPath}`);

    return outputPath;
  }
}
