// ArchLens — Artifact Reference IPC handlers

import { ipcMain, app, shell, dialog, BrowserWindow } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { ArtifactService, Artifact, ArtifactCategory, ProjectPhase } from '../services/artifact-service';
import { ipcSuccess, ipcError } from '../errors';

// ---------------------------------------------------------------------------
// Template generation helpers
// ---------------------------------------------------------------------------

async function generateWordTemplate(artifact: Artifact, filePath: string): Promise<void> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');

  const children: any[] = [];

  // Title
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [new TextRun({ text: artifact.name, bold: true, size: 48, color: '1a1a2e' })],
  }));

  // Metadata
  children.push(new Paragraph({
    spacing: { after: 100 },
    children: [new TextRun({ text: 'Date: [Enter date]', size: 22, color: '666666' })],
  }));
  children.push(new Paragraph({
    spacing: { after: 100 },
    children: [new TextRun({ text: 'Author: [Enter author name]', size: 22, color: '666666' })],
  }));
  children.push(new Paragraph({
    spacing: { after: 100 },
    children: [new TextRun({ text: 'Version: 1.0', size: 22, color: '666666' })],
  }));
  children.push(new Paragraph({
    spacing: { after: 400 },
    children: [new TextRun({ text: 'Status: Draft', size: 22, color: '666666' })],
  }));

  // Purpose
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text: 'Purpose', bold: true })],
  }));
  children.push(new Paragraph({
    spacing: { after: 300 },
    children: [new TextRun({ text: artifact.purpose, italics: true, color: '555555' })],
  }));

  // Template sections
  for (const section of artifact.templateSections) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 300 },
      children: [new TextRun({ text: section.heading, bold: true })],
    }));
    children.push(new Paragraph({
      spacing: { after: 100 },
      children: [new TextRun({ text: `Guidance: ${section.guidance}`, italics: true, color: '888888', size: 20 })],
    }));
    children.push(new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({ text: section.placeholder, color: '444444' })],
    }));
    // Empty space for user content
    children.push(new Paragraph({ spacing: { after: 200 }, children: [] }));
  }

  // Footer
  children.push(new Paragraph({
    spacing: { before: 600 },
    children: [new TextRun({ text: `Generated by ArchLens — ${new Date().toLocaleDateString('en-GB')}`, italics: true, color: '999999', size: 18 })],
  }));

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);
}

async function generateExcelTemplate(artifact: Artifact, filePath: string): Promise<void> {
  const ExcelJS = await import('exceljs');
  const workbook = new ExcelJS.Workbook();

  // Info sheet
  const infoSheet = workbook.addWorksheet('Info');
  infoSheet.columns = [
    { header: 'Field', key: 'field', width: 20 },
    { header: 'Value', key: 'value', width: 60 },
  ];
  infoSheet.addRow({ field: 'Document', value: artifact.name });
  infoSheet.addRow({ field: 'Date', value: '[Enter date]' });
  infoSheet.addRow({ field: 'Author', value: '[Enter author name]' });
  infoSheet.addRow({ field: 'Version', value: '1.0' });
  infoSheet.addRow({ field: 'Status', value: 'Draft' });
  infoSheet.addRow({ field: 'Purpose', value: artifact.purpose });

  // Style the header row
  infoSheet.getRow(1).font = { bold: true };
  infoSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4A6CF7' } };
  infoSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  // Main template sheet
  const mainSheet = workbook.addWorksheet(artifact.name.substring(0, 31));

  // Use template sections as columns for tabular artifacts
  const headers = artifact.templateSections.map(s => s.heading);
  mainSheet.columns = headers.map(h => ({ header: h, key: h, width: 30 }));

  // Style header row
  mainSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  mainSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4A6CF7' } };
  mainSheet.getRow(1).alignment = { wrapText: true, vertical: 'middle' };

  // Add guidance row
  const guidanceRow = mainSheet.addRow(
    artifact.templateSections.reduce((acc, s) => {
      acc[s.heading] = s.guidance;
      return acc;
    }, {} as Record<string, string>)
  );
  guidanceRow.font = { italic: true, color: { argb: 'FF888888' } };
  guidanceRow.alignment = { wrapText: true };

  // Add example/placeholder row
  mainSheet.addRow(
    artifact.templateSections.reduce((acc, s) => {
      acc[s.heading] = s.placeholder;
      return acc;
    }, {} as Record<string, string>)
  );

  // Add 20 empty rows for the user to fill in
  for (let i = 0; i < 20; i++) {
    mainSheet.addRow({});
  }

  // Auto-filter on headers
  mainSheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: headers.length },
  };

  await workbook.xlsx.writeFile(filePath);
}

/**
 * Registers IPC handlers for the `artifacts` namespace.
 *
 * Channels:
 *  - `artifacts.getAll`           → returns all artifacts
 *  - `artifacts.getByCategory`    → filters by category
 *  - `artifacts.getByPhase`       → filters by project phase
 *  - `artifacts.getByFramework`   → filters by framework
 *  - `artifacts.search`           → full-text search
 *  - `artifacts.getById`          → single artifact by ID
 *  - `artifacts.generateTemplate` → returns markdown template string
 *  - `artifacts.downloadTemplate` → saves markdown template to user-chosen location
 */
export function registerArtifactHandlers(artifactService: ArtifactService): void {
  ipcMain.handle('artifacts.getAll', () => {
    try {
      const artifacts = artifactService.getAll();
      return ipcSuccess(artifacts);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.getByCategory', (_event, category: ArtifactCategory) => {
    try {
      const artifacts = artifactService.getByCategory(category);
      return ipcSuccess(artifacts);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.getByPhase', (_event, phase: ProjectPhase) => {
    try {
      const artifacts = artifactService.getByPhase(phase);
      return ipcSuccess(artifacts);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.getByFramework', (_event, framework: string) => {
    try {
      const artifacts = artifactService.getByFramework(framework);
      return ipcSuccess(artifacts);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.search', (_event, query: string) => {
    try {
      const artifacts = artifactService.search(query);
      return ipcSuccess(artifacts);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.getById', (_event, id: string) => {
    try {
      const artifact = artifactService.getById(id);
      return ipcSuccess(artifact);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.generateTemplate', (_event, artifactId: string) => {
    try {
      const markdown = artifactService.generateMarkdownTemplate(artifactId);
      return ipcSuccess(markdown);
    } catch (err) {
      return ipcError(err);
    }
  });

  ipcMain.handle('artifacts.downloadTemplate', async (_event, artifactId: string) => {
    try {
      const artifact = artifactService.getById(artifactId);
      if (!artifact) {
        return ipcError(new Error(`Artifact not found: ${artifactId}`));
      }

      const sanitisedName = artifact.name
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-');

      // Determine if this artifact is better as a spreadsheet
      const spreadsheetArtifacts = [
        'raci-matrix', 'risk-register', 'issue-log', 'stakeholder-map',
        'information-asset-register', 'vendor-assessment-matrix',
        'data-dictionary', 'data-quality-assessment', 'backlog',
        'burndown-chart', 'capacity-plan', 'gate-review-checklist',
        'tcop-checklist', 'lessons-learned-log',
      ];
      const isSpreadsheet = spreadsheetArtifacts.includes(artifactId);

      const ext = isSpreadsheet ? 'xlsx' : 'docx';
      const filterName = isSpreadsheet ? 'Excel Workbook' : 'Word Document';
      const defaultFileName = `${sanitisedName}-template.${ext}`;

      const win = BrowserWindow.getFocusedWindow();
      const result = await dialog.showSaveDialog(win!, {
        title: 'Save Template',
        defaultPath: path.join(app.getPath('documents'), defaultFileName),
        filters: [
          { name: filterName, extensions: [ext] },
          { name: 'All Files', extensions: ['*'] },
        ],
      });

      if (result.canceled || !result.filePath) {
        return ipcSuccess({ saved: false });
      }

      if (isSpreadsheet) {
        await generateExcelTemplate(artifact, result.filePath);
      } else {
        await generateWordTemplate(artifact, result.filePath);
      }

      // Open the containing folder
      shell.showItemInFolder(result.filePath);

      return ipcSuccess({ saved: true, filePath: result.filePath });
    } catch (err) {
      return ipcError(err);
    }
  });
}
